- name: Check httpd service
  hosts: all
  tasks:
    - name: Obtiene estado de httpd
      command: systemctl status httpd
      register: estado

    - name: Inicia assert
      assert:
        that: estado.changed == True

