- name: Check httpd service
  hosts: all
  tasks:
    - name: Obtiene estado de httpd
      command: service status httpd
      register: estado

    - name: Inicia assert
      assert: estado.changed == True
